# Netlify configuration for thebluedrops.com
[build]
  publish = "dist"
  command = "npm run build"

# SPA routing - All routes redirect to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Domain configuration
[context.production]
  environment = { NODE_ENV = "production" }

# Branch deploys
[context.branch-deploy]
  command = "npm run build"

# Deploy previews
[context.deploy-preview]
  command = "npm run build"