# Netlify configuration for thebluedrops.com
[build]
  publish = "dist"
  command = "npm run build"

# Force redirect from www to non-www
[[redirects]]
  from = "https://www.thebluedrops.com/*"
  to = "https://thebluedrops.com/:splat"
  status = 301
  force = true

# Alternative: Allow both www and non-www (comment out the above and use this instead)
# [[redirects]]
#   from = "https://thebluedrops.com/*"
#   to = "https://www.thebluedrops.com/:splat"
#   status = 301
#   force = true

# Redirect rules for clean URLs and slug support
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/home/"
  to = "/"
  status = 301

# Upsell pages
[[redirects]]
  from = "/up1bt/"
  to = "/up1bt"
  status = 301

[[redirects]]
  from = "/up3bt/"
  to = "/up3bt"
  status = 301

[[redirects]]
  from = "/up6bt/"
  to = "/up6bt"
  status = 301

# Second upsell pages
[[redirects]]
  from = "/upig1bt/"
  to = "/upig1bt"
  status = 301

[[redirects]]
  from = "/upig3bt/"
  to = "/upig3bt"
  status = 301

[[redirects]]
  from = "/upig6bt/"
  to = "/upig6bt"
  status = 301

# Downsell pages
[[redirects]]
  from = "/dws1/"
  to = "/dws1"
  status = 301

[[redirects]]
  from = "/dws2/"
  to = "/dws2"
  status = 301

[[redirects]]
  from = "/dw3/"
  to = "/dw3"
  status = 301

# Other pages
[[redirects]]
  from = "/ftr/"
  to = "/ftr"
  status = 301

[[redirects]]
  from = "/admin/"
  to = "/admin"
  status = 301

[[redirects]]
  from = "/thankyou/"
  to = "/thankyou"
  status = 301

[[redirects]]
  from = "/lpw/"
  to = "/lpw"
  status = 301

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"