# Netlify configuration for thebluedrops.com
[build]
  publish = "dist"
  command = "npm run build"

# Force redirect from www to non-www (MUST be first)
[[redirects]]
  from = "https://www.thebluedrops.com/*"
  to = "https://thebluedrops.com/:splat"
  status = 301
  force = true

# Clean URL redirects (remove trailing slashes)
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/home/"
  to = "/"
  status = 301


# SPA fallback - MUST be last and MOST IMPORTANT
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"